### ISSUE TITLE
Auto-bump mapping API version

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-cli#233]
If a subgraph has defined a mapping API version that is behind the version of `graph-ts` being used: auto-bump the mapping API version in the subgraph manifest to the compatible version. 
  
Perform the bump of the mapping API version during `build`.

**Comment by Jannis** [comment]
It would be good if this was done in all of `codegen`, `build` and `deploy`.

I think a good design would be a sequence of migrations, each with a predicate function and a migrate function (and perhaps a skip predicate function?). At minimum each of these functions could receive:
- the subgraph filename (because that doesn't have to be `subgraph.yaml`)
- the working directory (so it can access `package.json`)
- the loaded subgraph manifest (maybe `undefined` if loading failed, to allow migrations to fix manifests)

We could then apply each migration in turn and try to reload the subgraph manifest after every migration. If any of the migrations throw an error, we abort.

It seems reasonable to me to run this in its own CLI spinner.
