### ISSUE TITLE
Yarn workspaces: '~lib/@graphprotocol/graph-ts.ts' not found

### ISSUE THREAD

**Issue by pi0neerpat** [graphprotocol/graph-cli#479]
## Issue

When using Lerna and Yarn workspaces, the command `graph deploy` fails with error: 

```
✔ Load subgraph from subgraph.yaml
  Compile data source: Gravity => build/Gravity/Gravity.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
Error: Failed to compile data source mapping: Import file '~lib/@graphprotocol/graph-ts.ts' not found.
    at Compiler._compileDataSourceMapping (/home/thisguy/repos/graph-cli-testing/node_modules/@graphprotocol/graph-cli/src/compiler.js:308:13)
    at /home/thisguy/repos/graph-cli-testing/node_modules/@graphprotocol/graph-cli/src/compiler.js:184:20
    at updateInDeepMap (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/thisguy/repos/graph-cli-testing/node_modules/@graphprotocol/graph-cli/src/compiler.js:183:24
    at /home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/home/thisguy/repos/graph-cli-testing/node_modules/immutable/dist/immutable.js:3015:23)
```

Talking with @Jannis on Discord, he suggested the reason: 

> AssemblyScript compiler doesn't have built-in module resolution, so what graph-cli does is try to find a node_modules folder in the current directory or any parent directories, in order to resolve e.g. @graphprotocol/graph-ts.

## Expected Behavior

Should be able to install and use graph-cli in a Yarn workspaces monorepo

## Reproduce this issue

I made an example repo here: https://github.com/pi0neerpat/graph-cli-testing-example

**Comment by pi0neerpat** [comment]
@fubhy has added a fix in https://github.com/graphprotocol/graph-cli/pull/478

Until then, he suggested using `nohoist` to address the problem. You MUST set `private: true` in package.json for yarn to respect nohoist. Here is what mine looks like:

```json
{
  "name": "subgraph",
  "version": "0.1.0",
  "private": true,
   ...
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.18.0",
    "@graphprotocol/graph-ts": "^0.18.0"
  },
  "workspaces": {
    "nohoist": [
      "**/@graphprotocol",
      "**/@graphprotocol/**"
    ]
  }
}

**Comment by sesameJar** [comment]
I get the same error anytime I tried to build, deploy ... and this solution did not solved it. 
I checked your test-example repo and copy paste the `generated` directory into mine and that solved the problem. 
I wonder why the folder was missing. I also checked the original example repo and it was also missing there. I am not sure how to create this `generated` directory on my own project. 

Another issue that I also get is the node-gyp build anytime I `graph init` or `npm install`. This is the error : 
`error /Users/mehradkavian/Dropbox/graphQL/sub1/node_modules/sha3: Command failed.
Exit code: 127
Command: node-gyp rebuild
Arguments: 


`

I thought this missing error that I get from create or deploy(either local or hosted) might have been because of this error.
I don't know what I'm missing.
