### ISSUE TITLE
My subgraph has been successfully deployed, but the synchronization status is failed, and there is no reason for failure

### ISSUE THREAD

**Issue by kl521516** [graphprotocol/graph-cli#668]
https://thegraph.com/explorer/subgraph/kl521516/fourth

My subgraph has been successfully deployed, but the synchronization status is failed, and there is no reason for failure

**Comment by schmidsi** [comment]
There are now logs describing what went wrong:

https://thegraph.com/explorer/subgraph/kl521516/fourth?selected=logs -->

> Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 73, column 6, with message: Ethereum value is not a string. wasm backtrace: 0: 0xe72 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.Value#toString 1: 0x1015 - <unknown>!src/mapping/handlereg_event in handler `handlereg_event` at block #8658226 (89e0b25ce866fe40f7cfd7b6fcfa8cf9cc97878a9ad20021018adb26d1f38773), code: SubgraphSyncingFailure

Sometimes, the logs on the hosted service are not up to date. I recommend running a local graph-node on your computer and deploy there first.

Closing this, since there is now a reason for the failure. Feel free to reopen if you need more support.
