### ISSUE TITLE
Add graph init support for NEAR

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-cli#772]
NEAR subgraphs are different to Ethereum subgraphs (no ABIs, different manifest structure). We should update `graph init` to scaffold a NEAR subgraph from scratch

Follow on to: https://github.com/graphprotocol/graph-cli/issues/734

Draft specification: https://hackmd.io/pAZQK4I7T4O_BiCKHKcH_g

**Comment by otaviopace** [comment]
After studying our current implementation and the [hackmd spec](https://hackmd.io/pAZQK4I7T4O_BiCKHKcH_g), I've made some notes on how I intend to follow up with this, related to behavior (current vs after), open questions and implementation plan (to know where I should change and how big the task is).

# Behavior (current vs after)

## Prompt questions

`graph init` asks multiple questions so it can generate the subgraph.

These questions can or not be skipped based of if the user has sent value through their respective flags directly.

### Current

Here are the values we ask **currently**:

1. product (hosted-service|studio)
- skip:
  - if passed any via flags such as `--product` or `--studio`
2. subgraph name
3. directory
4. network
- choices:
  - EVM compatible ones
- skip:
  - if it is `--from-example`
5. address
- used for:
  - validation
  - fetching from EtherScan if file is not provided by `--abi`
6. ABI
- used for:
  - validation
7. contract name

### After

The **new** set of questions proposed is:

1. **(new)** protocol/chain (evm-compat|near)
2. product (hosted-service|studio)
- skip:
  - if passed any via flags such as `--product` or `--studio`
  - **(new)** if the protocol/chain is NEAR (we'll only support `hosted-service` for now)
3. subgraph name
4. directory
5. network
- choices:
  - **(new)** EVM compatible vs NEAR ones based of chain/protocol
- skip:
  - if it is `--from-example`
6. **(new, name and validation change based of protocol)** address or account
- used for:
  - validation
  - evm:
    - fetching from EtherScan if file is not provided by `--abi`
  - **(new)** near:
    - validate contract exists on the NEAR Explorer?
7. ABI
- **(new)** skip:
  - if the chain doesn't have them (eg: NEAR)
- used for:
  - validation
7. contract name

## CLI `--help` format

### Current

**Now** our `graph init --help` returns:

```
graph init [options] [subgraph-name] [directory]

Options:

      --product <subgraph-studio|hosted-service>
                                Selects the product for which to initialize
      --studio                  Shortcut for --product subgraph-studio
  -g, --node <node>             Graph node for which to initialize
      --allow-simple-name       Use a subgraph name without a prefix (default: false)
  -h, --help                    Show usage information

Choose mode with one of:

      --from-contract <address> Creates a scaffold based on an existing contract
      --from-example            Creates a scaffold based on an example subgraph

Options for --from-contract:

      --abi <path>              Path to the contract ABI (default: download from Etherscan)
      --network <mainnet|kovan|rinkeby|ropsten|goerli|poa-core|poa-sokol|xdai|matic|mumbai|fantom|bsc|chapel|clover|avalanche|fuji|celo|celo-alfajores|fuse|mbase|arbitrum-one|arbitrum-rinkeby|optimism|optimism-kovan>
                                Selects the network the contract is deployed to
      --index-events            Index contract events as entities
      --contract-name           Name of the contract (default: Contract)
```

### After

Adding the `--chain/protocol` is very straightforward, the problem comes for flags that are not supported by a chain (eg: `--abi` for NEAR).

My suggestion is to do it like shown down below, whereas we'll have a specific section for each chain/protocol:

```
graph init [options] [subgraph-name] [directory]

Options:

      --protocol <evm-compat|near>
      --product <subgraph-studio|hosted-service>
                                Selects the product for which to initialize
      --studio                  Shortcut for --product subgraph-studio
  -g, --node <node>             Graph node for which to initialize
      --allow-simple-name       Use a subgraph name without a prefix (default: false)
  -h, --help                    Show usage information

Choose mode with one of:

      --from-contract <address> Creates a scaffold based on an existing contract
      --from-example            Creates a scaffold based on an example subgraph

Options for --from-contract:

      --contract-name           Name of the contract (default: Contract)
      --index-events            Index contract events as entities

EVM compatible:

      --abi <path>              Path to the contract ABI (default: download from Etherscan)
      --network <mainnet|kovan|rinkeby|ropsten|goerli|poa-core|poa-sokol|xdai|matic|mumbai|fantom|bsc|chapel|clover|avalanche|fuji|celo|celo-alfajores|fuse|mbase|arbitrum-one|arbitrum-rinkeby|optimism|optimism-kovan>
                                Selects the network the contract is deployed to

NEAR:

      --network <mainnet|testnet>
                                Selects the network the contract is deployed to

```

Also, on this I accept suggestions for the `--protocol` description 🙂 

## Open Questions

1. Should the chain question (Ethereum vs NEAR) use the term `--chain` or `--protocol`? IMO it should be `--protocol` so it's less strange for when we support file data sources for example.
2. For the MVP should we just handle the `--from-contract` case or the `--from-example` as well? If it's both, should I clone the base from any of these branches (maybe just the receipts one for now)?
  - https://github.com/graphprotocol/example-subgraph/tree/near-blocks-example
  - https://github.com/graphprotocol/example-subgraph/tree/near-receipts-example
3. In the `--from-contract` option, should we validate the contract exists on the [NEAR Explorer](https://explorer.near.org/) for better developer experience (lower feedback loop)?
  - About this, I don't know if `graph-node` validates that somehow on `deploy` or if it breaks when the subgraph starts indexing (trying to).

## Implementation plan

- Prompt questions:
  - Change [this](https://github.com/graphprotocol/graph-cli/blob/master/src/commands/init.js#L95) so it follows up the behavior desired described above
- [Scaffold](https://github.com/graphprotocol/graph-cli/blob/master/src/scaffold.js)
  - We need to extract/change/move the file generation of:
    - `subgraph.yaml`: format in general, to respect chain's schema
    - `schema.graphql`: remove ABI related things
    - `src/mapping.ts`: create switch for handler names and remove ABI related things
    - `abis/`: remove folder for when protocol doesn't have ABIs (eg: NEAR)
  - And this requires:
    - A class for each chain (2 new ones)
    - Instantiate the `Protocol` class on `src/commands/init.js` and pass it to `src/scaffold.js`
- `graph init` tests
  - Add `--chain/protocol evm-compat` flag for all of the tests [here](https://github.com/graphprotocol/graph-cli/blob/master/tests/cli/init.test.js)
  - Add NEAR test for `--from-contract`
  - Add NEAR test for `--from-example`
    - Either saying that it isn't supported yet via warning/error message **or** with the correct generated results

The summary for this part is that it won't be hard, just a lot of refactor/moving code around, making sure we don't break anything (and the new NEAR code works as well).

**Comment by leoyvens** [comment]
Thanks for the detailed plan! We went with `protocol` in the graph node configuration, however in the manifest this is still called `kind` with the values `near | ethereum`. Whatever name we choose, I think the value should be `ethereum` rather than `evm-compat`, though maybe we can display `Ethereum and EVM-compatible`.
